import "./assets/styles/main.scss"
import "./assets/scripts/loader"
import "./assets/scripts/pulseHover"
import "./assets/scripts/greeting"
import "./assets/scripts/burger"
import "./assets/scripts/challenge"
import "glsl-component"